export const PACKAGING = "PACKAGING";
export const PACKAGING_SUCCESSFUL = "PACKAGING_SUCCESSFUL";
export const PACKAGING_FAILED = "PACKAGING_FAILED";
export const RESET_PACKAGING_FLAG = "RESET_PACKAGING_FLAG";