export const NEW_PROJECT = "NEW_PROJECT";
export const NEW_PROJECT_SUCCESSFUL = "NEW_PROJECT_SUCCESSFUL";
export const NEW_PROJECT_FAILED = "NEW_PROJECT_FAILED";
export const RESET_NEW_PROJECT_FLAG = "RESET_NEW_PROJECT_FLAG";
