export const FORMULATION = "FORMULATION";
export const FORMULATION_SUCCESSFUL = "FORMULATION_SUCCESSFUL";
export const FORMULATION_FAILED = "FORMULATION_FAILED";
export const RESET_FORMULATION_FLAG = "RESET_FORMULATION_FLAG";


