export const MANUFACTURING = "MANUFACTURING";
export const MANUFACTURING_SUCCESSFUL = "MANUFACTURING_SUCCESSFUL";
export const MANUFACTURING_FAILED = "MANUFACTURING_FAILED";
export const RESET_MANUFACTURING_FLAG = "RESET_MANUFACTURING_FLAG";


